# Generated by Django 3.1.1 on 2021-02-26 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='UserProfile',
        ),
    ]
