# Generated by Django 3.1.1 on 2021-02-27 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_auto_20210227_0800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='id',
        ),
        migrations.AlterField(
            model_name='resume',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='details', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
